base_dir: http://localhost:5000
image_dir: http://localhost:5000/img
master_password: yourpassword
special_password: yourspecialpassword
admin_name: 管理者の名前
admin_email: root@localhost.localdomain
bbs_url: http://localhost/bbs.cgi
toppage_url: http://localhost/index.html
data_dir: data
lock_mode: 2

unit_time: 43200
unlock_time: 120
max_island: 30
top_log_turn: 1
log_max: 8
backup_turn: 12
backup_times: 4
history_max: 10
giveup_turn: 28
command_max: 20
use_local_bbs: 1
local_bbs_max: 10
island_size: 12
hide_money_mode: 2
crypt: 1
debug: 0

initial_money: 100
initial_food: 100
unit_money: 億円
unit_food: 00トン
unit_population: 00人
unit_area: 00万坪
unit_tree: 00本
tree_value: 5
change_name_cost: 500
eaten_food: 0.2

max_exp_point: 200
max_base_level: 5
max_sea_base_level: 3
base_level_up:
  - 20
  - 60
  - 120
  - 200
sea_base_level_up:
  - 50
  - 200

defence_base_auto: 1

disaster_earthquake: 5
disaster_tsunami: 15
disaster_typhoon: 20
disaster_meteo: 15
disaster_huge_meteo: 5
disaster_eruption: 10
disaster_fire: 10
disaster_maizo: 10
disaster_fall_border: 90
disaster_fall_down: 30
disaster_monster_border1: 1000
disaster_monster_border2: 2500
disaster_monster_border3: 4000
disaster_monster: 1
monster_number: 8
monster_level1: 2
monster_level2: 5
monster_level3: 7
monster_name:
  - メカいのら
  - いのら
  - サンジラ
  - レッドいのら
  - ダークいのら
  - いのらゴースト
  - クジラ
  - キングいのら
monster_bottom_hp:
  - 2
  - 1
  - 1
  - 3
  - 2
  - 1
  - 4
  - 5
monster_dhp:
  - 0
  - 2
  - 2
  - 2
  - 2
  - 0
  - 2
  - 2
monster_special:
  - 0
  - 0
  - 3
  - 0
  - 1
  - 2
  - 4
  - 0
monster_exp:
  - 5
  - 5
  - 7
  - 12
  - 15
  - 10
  - 20
  - 30
monster_value:
  - 0
  - 400
  - 500
  - 1000
  - 800
  - 300
  - 1500
  - 2000
monster_image:
  - monster7.gif
  - monster0.gif
  - monster5.gif
  - monster1.gif
  - monster2.gif
  - monster8.gif
  - monster6.gif
  - monster3.gif
monster_image2:
  - ""
  - ""
  - monster4.gif
  - ""
  - ""
  - ""
  - monster4.gif
  - ""

oil_money: 1000
oil_ratio: 40

monument_number: 3
monument_name:
  - モノリス
  - 平和記念碑
  - 戦いの碑
monument_image:
  - monument0.gif
  - monument0.gif
  - monument0.gif

turn_prize_unit: 100
prize:
  - ターン杯
  - 繁栄賞
  - 超繁栄賞
  - 究極繁栄賞
  - 平和賞
  - 超平和賞
  - 究極平和賞
  - 災難賞
  - 超災難賞
  - 究極災難賞

html_body: 'BGCOLOR="#EEFFFF"'
title: 箱庭諸島２
tag_title_: '<FONT SIZE=7 COLOR="#8888ff">'
_tag_title: '</FONT>'
tag_header_: '<FONT COLOR="#4444ff">'
_tag_header: '</FONT>'
tag_big_: '<FONT SIZE=6>'
_tag_big: '</FONT>'
tag_name_: '<FONT COLOR="#a06040"><B>'
_tag_name: '</B></FONT>'
tag_name2_: '<FONT COLOR="#808080"><B>'
_tag_name2: '</B></FONT>'
tag_number_: '<FONT COLOR="#800000"><B>'
_tag_number: '</B></FONT>'
tag_th_: '<FONT COLOR="#C00000"><B>'
_tag_th: '</B></FONT>'
tag_com_name_: '<FONT COLOR="#d08000"><B>'
_tag_com_name: '</B></FONT>'
tag_disaster_: '<FONT COLOR="#ff0000"><B>'
_tag_disaster: '</B></FONT>'
tag_local_bbs_ss_: '<FONT COLOR="#0000ff"><B>'
_tag_local_bbs_ss: '</B></FONT>'
tag_local_bbs_ow_: '<FONT COLOR="#ff0000"><B>'
_tag_local_bbs_ow: '</B></FONT>'
normal_color: "#000000"
bg_title_cell: 'BGCOLOR="#ccffcc"'
bg_number_cell: 'BGCOLOR="#ccffcc"'
bg_name_cell: 'BGCOLOR="#ccffff"'
bg_info_cell: 'BGCOLOR="#ccffff"'
bg_comment_cell: 'BGCOLOR="#ccffcc"'
bg_input_cell: 'BGCOLOR="#ccffcc"'
bg_map_cell: 'BGCOLOR="#ccffcc"'
bg_command_cell: 'BGCOLOR="#ccffcc"'
