requires 'Plack';
requires 'YAML';
requires 'List::MoreUtils';
requires 'DBI';
requires 'DBD::mysql';
requires 'Text::Xslate';
requires 'Router::Simple';
requires 'Plack::Session::Store::DBI';
requires 'Hash::Merge';
requires 'Exception::Tiny';
requires 'Test::More'
